version: '3.1'

services:
  database:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=hosting"
    ports:
      - "33061:3306"
    volumes:
      - ./mysql:/var/lib/mysql
